=== OPTANO/optano.algorithm.tuner/Source/Optano.Algorithm.Tuner.Tests/parameterTree.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="node" type="Node" />

  <xs:complexType name="and">
    <xs:complexContent mixed="false">
      <xs:extension base="Node">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="node" type="Node" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Node" abstract="true" />

  <xs:complexType name="ParameterNode" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="Node">
        <xs:sequence>
          <xs:element name="domain" type="Domain"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Domain" abstract="true" >
    <xs:attribute name="defaultIndexOrValue" type="xs:double"/>
  </xs:complexType>

  <xs:complexType name="continuous">
    <xs:complexContent mixed="false">
      <xs:extension base="Domain">
        <xs:attribute name="log" type="xs:boolean" default="false" />
        <xs:attribute name="start" type="xs:double" use="required" />
        <xs:attribute name="end" type="xs:double" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="discrete">
    <xs:complexContent mixed="false">
      <xs:extension base="Domain">
        <xs:attribute name="log" type="xs:boolean" default="false" />
        <xs:attribute name="start" type="xs:int" use="required" />
        <xs:attribute name="end" type="xs:int" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

	<xs:complexType name="categorical">
		<xs:complexContent mixed="false">
			<xs:extension base="Domain">
				<xs:attribute name="doubles" type="doubles" />
				<xs:attribute name="strings" type="strings" />
				<xs:attribute name="ints" type="ints" />
				<xs:attribute name="booleans" type="booleans" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="strings">
		<xs:list itemType="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="ints">
		<xs:list itemType="xs:int" />
	</xs:simpleType>

	<xs:simpleType name="doubles">
		<xs:list itemType="xs:double" />
	</xs:simpleType>

	<xs:simpleType name="booleans">
		<xs:list itemType="xs:boolean" />
	</xs:simpleType>

  <xs:complexType name="or">
    <xs:complexContent mixed="false">
      <xs:extension base="ParameterNode">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="choice" type="Choice" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Choice">
		<xs:sequence>
			<xs:choice>
				<xs:element name="string" type="xs:string"/>
				<xs:element name="boolean" type="xs:boolean"/>
				<xs:element name="int" type="xs:int"/>
				<xs:element name="double" type="xs:double"/>
			</xs:choice>
		  <xs:element name="child" type="Node" />
		</xs:sequence>
  </xs:complexType>

  <xs:complexType name="value">
    <xs:complexContent mixed="false">
      <xs:extension base="ParameterNode">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="node" type="Node" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== OPTANO/optano.algorithm.tuner/Source/Optano.Algorithm.Tuner.Tests/ParameterTreeReader/TestData/exampleTree.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- Root is an AND node. -->
<node xsi:type="and" xsi:noNamespaceSchemaLocation="../../../Optano.Algorithm.Tuner/parameterTree.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<!-- AND node's children are a double OR node and a double value node. -->
	<node xsi:type="or" id="or">
		<domain xsi:type="categorical" doubles="0.1 0.3 0.5" defaultIndexOrValue="1" />
		<!-- OR node's children is an AND node activated on 0.1 and a discrete value node activated on 0.5. -->
		<choice>
			<double>0.1</double>
			<child xsi:type="and" />
		</choice>
		<choice>
			<double>0.5</double>
			<child xsi:type="value" id="value1">
				<domain xsi:type="discrete" start="-2" end="3"/>
			</child>
		</choice>
	</node>
	<node xsi:type="value" id="value2">
		<domain xsi:type="continuous" start="-0.1" end="0.0"/>
		<!-- 1st level value node has another value node with a log domain as child. -->
		<node xsi:type="value" id="value3">
			<domain xsi:type="continuous" log="true" start="10" end="100"/>
		</node>
	</node>
</node>
